version: '8.0'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=fasters
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
